services:
    _defaults:
        public: false

    artox_lab_sms.prototype.provider.sms_line:
        class: ArtoxLab\Bundle\SmsBundle\Provider\SmsLineProvider

    artox_lab_sms.prototype.provider.lets_ads:
        class: ArtoxLab\Bundle\SmsBundle\Provider\LetsAdsProvider

    artox_lab_sms.prototype.provider.infobip:
        class: ArtoxLab\Bundle\SmsBundle\Provider\InfobipProvider

    artox_lab_sms.prototype.provider.mail:
        class: ArtoxLab\Bundle\SmsBundle\Provider\MailProvider

    artox_lab_sms.prototype.provider.log:
        class: ArtoxLab\Bundle\SmsBundle\Provider\LogProvider
        arguments:
          ['@logger']
        tags:
            - { name: monolog.logger}

    artox_lab_sms.prototype.provider.slack:
        class: ArtoxLab\Bundle\SmsBundle\Provider\SlackProvider

    artox_lab_sms.provider.manager:
        class: ArtoxLab\Bundle\SmsBundle\Service\ProviderManager

    ArtoxLab\Bundle\SmsBundle\Service\ProviderManager: '@artox_lab_sms.provider.manager'
