services:
    _defaults:
        public: false

    artox_lab_sms.prototype.provider.sms_line:
        class: ArtoxLab\Bundle\SmsBundle\Provider\SmsLineProvider

    artox_lab_sms.prototype.provider.lets_ads:
        class: ArtoxLab\Bundle\SmsBundle\Provider\LetsAdsProvider

    artox_lab_sms.prototype.provider.infobip:
        class: ArtoxLab\Bundle\SmsBundle\Provider\InfobipProvider

    artox_lab_sms.provider.manager:
        class: ArtoxLab\Bundle\SmsBundle\Service\ProviderManager

    ArtoxLab\Bundle\SmsBundle\Service\ProviderManager: '@artox_lab_sms.provider.manager'
